import type { CalendarTag, ClassEntry } from './timetable-types';

export const scheduleByDay: Record<string, ClassEntry[]> = {
  mon: [
    {
      id: 'mon-1',
      title: 'DBMS',
      teacher: 'Prof. Deshmukh',
      room: 'LH 19',
      start: '08:45',
      end: '09:45',
      type: 'Lecture',
      note: 'Parallel database basics and attendance check.',
    },
    {
      id: 'mon-2',
      title: 'Project Management',
      teacher: 'Dr. Kulkarni',
      room: 'LH 20',
      start: '09:50',
      end: '10:45',
      type: 'Lecture',
      note: 'Sprint review and assignment tracker.',
    },
    {
      id: 'mon-3',
      title: 'DBMS Lab',
      teacher: 'Prof. Deshmukh',
      room: 'VI Lab',
      start: '11:00',
      end: '12:45',
      type: 'Lab',
      note: 'Assignment 7 submission in PL/SQL.',
    },
    {
      id: 'mon-4',
      title: 'Probability & Statistics',
      teacher: 'Prof. Shah',
      room: 'LH 18',
      start: '13:45',
      end: '14:45',
      type: 'Tutorial',
      note: 'Permutation and combination problem set.',
    },
  ],
  tue: [
    {
      id: 'tue-1',
      title: 'Computer Graphics',
      teacher: 'Prof. Patil',
      room: 'LH 21',
      start: '08:45',
      end: '09:45',
      type: 'Lecture',
    },
    {
      id: 'tue-2',
      title: 'DBMS',
      teacher: 'Prof. Deshmukh',
      room: 'LH 19',
      start: '09:50',
      end: '10:45',
      type: 'Lecture',
      note: 'Distributed database overview.',
    },
    {
      id: 'tue-3',
      title: 'E-Commerce',
      teacher: 'Prof. Ghule',
      room: 'Tut Room',
      start: '12:45',
      end: '13:45',
      type: 'Tutorial',
      note: 'Security tools and best practices.',
    },
  ],
  wed: [
    {
      id: 'wed-1',
      title: 'Computer Graphics Lab',
      teacher: 'Prof. Patil',
      room: 'Lab III',
      start: '08:45',
      end: '10:45',
      type: 'Lab',
    },
    {
      id: 'wed-2',
      title: 'Project Management',
      teacher: 'Dr. Kulkarni',
      room: 'LH 20',
      start: '11:00',
      end: '12:00',
      type: 'Lecture',
    },
    {
      id: 'wed-3',
      title: 'EVS',
      teacher: 'Prof. More',
      room: 'LH 16',
      start: '14:45',
      end: '15:45',
      type: 'Lecture',
      note: 'Short lecture before placement session.',
    },
  ],
  thu: [
    {
      id: 'thu-1',
      title: 'Holiday',
      teacher: 'AIT',
      room: 'Campus',
      start: '00:00',
      end: '23:59',
      type: 'Deadline',
      note: 'No classes scheduled.',
    },
  ],
  fri: [
    {
      id: 'fri-1',
      title: 'Machine Learning',
      teacher: 'Prof. Jadhav',
      room: 'LH 17',
      start: '08:45',
      end: '09:45',
      type: 'Lecture',
    },
    {
      id: 'fri-2',
      title: 'CG Lab',
      teacher: 'Prof. Patil',
      room: 'Lab II',
      start: '11:00',
      end: '12:45',
      type: 'Lab',
      note: 'Painter algorithm revision and viva prep.',
    },
  ],
  sat: [
    {
      id: 'sat-1',
      title: 'Timetable Refresh',
      teacher: 'Sentri',
      room: 'Share Sheet',
      start: '10:00',
      end: '10:15',
      type: 'Deadline',
      note: 'Upload next week timetable screenshot here.',
    },
  ],
  sun: [],
};

export const calendarTags: Record<string, CalendarTag[]> = {
  '2026-03-23': [{ id: 'dbms', title: 'DBMS exam form', tone: 'blue' }],
  '2026-03-24': [{ id: 'resume', title: 'Resume check', tone: 'green' }],
  '2026-03-25': [{ id: 'cg', title: 'CG viva', tone: 'accent' }],
  '2026-03-26': [{ id: 'holiday', title: 'Holiday', tone: 'green' }],
  '2026-03-27': [{ id: 'pm', title: 'PM submission', tone: 'accent' }],
  '2026-03-28': [{ id: 'refresh', title: 'Upload timetable', tone: 'blue' }],
  '2026-03-31': [{ id: 'hackathon', title: 'Hackathon deadline', tone: 'accent' }],
  '2026-04-02': [{ id: 'placement', title: 'Placement drive', tone: 'green' }],
  '2026-04-04': [{ id: 'dbms-exam', title: 'DBMS exam', tone: 'blue' }],
};
